version: '3.8'
services:
  mongodb:
    container_name: filthy-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=core
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
volumes:
  data:
    external:
      name: mongodb





